name: Checking Clean Build
on:
  push:
    paths:
      - 'linux'
      
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - run: echo "The job was automatically triggered by a push event containing the changes in the commit number of the submodule linux"
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download
        run: wget -O latestCommit.zip https://github.com/camillejin/linux/archive/$(git rev-parse @:./linux).zip
            
      - name: Unzip
        run: unzip -qq latestCommit.zip
        
      - name: Build
        run: ./install-deps.sh
             ./build-linux.sh latestCommit tinyconfig
