name: Checking Clean Build
on:
  push:
    paths:
      - 'linux'
      
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - run: echo "The job was automatically triggered by a push event containing the changes in the commit number of the submodule linux"
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download and unzip
        run: wget https://github.com/camillejin/linux/archive/linux-$(git rev-parse @:./linux).zip
             unzip linux-$(git rev-parse @:./linux).zip
        
      - name: Build
        run: ./install-deps.sh
             ./build-linux.sh linux-$(git rev-parse @:./linux) tinyconfig
