name: Run Test
on:
  push:
    paths:
      - 'run_test/*'

jobs:
  build:
    runs-on: ubuntu-20.04
      
    steps:
      - uses: actions/checkout@v2

      - name: run test
        run: make -C run_test
             ./copy-files.sh
             ./run-qemu.sh
             ./run_test/*.exe
             
