name: Run Test
on:
  push:
    paths:
      - 'run_test/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: make file
        run: make -C run_test
        
      - name: Download
        run: wget https://github.com/OSS-SSH/linux/archive/$(git rev-parse @:./team_linux).zip
            
      - name: Unzip
        run: unzip -qq $(git rev-parse @:./team_linux).zip
        
      - name: Build
        run: ./install-deps.sh
             ./build-linux.sh $(git rev-parse @:./team_linux)
             ./create-image.sh
             ./copy-files.sh
             ./run-qemu.sh
             
      - name: Run Test
             ./run_test/test/test.exe


             
